### PR TITLE
Adding video recourses of Week 1 (lectures, live demo's and explainers)

### PR DESCRIPTION
**Pull request by Jelmerovereem**
**Added all the video recourses created in the first week of the Tech Track.**

I've embedded the videos as well, this does slow down the page. We could get rid of the embedded videos.

_Also beautified the HTML_

### CODE REVIEW

**Comment by Razpudding** [comment]
Thanks Jelmer, appreciate the input!
However, we are using static site generator 11ty to generate the HTML from the markdown files that are in the /pages folder. So If I accept your PR now, it will be overwritten the next time the website is built using 11ty.
@roberrrt-s any chance you could add this content to our markdown?

**Comment by Jelmerovereem** [comment]
Oohh, I didn't know that.
Thanks for the explanation!

**Comment by roberrrt-s** [comment]
I'll use this commit to change the .md files connected today, thanks @Jelmerovereem

**Comment by Razpudding** [comment]
Thanks @roberrrt-s really appreciate it!

**Pull request closed without merging**
